services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-devops-compose
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hello-devops-backend
    ports:
      - "3000:3000"